### PR TITLE
PR against issue #291 || UI changes

### PR DESCRIPTION
**Pull request by RahulBansal0502**
1. I have made the same header and footer of all the pages.
2.  Now footer will look like this:
image
3. I inserted the favicons and the title of each page.
4. Made changes in the UI of the About Page:
image
5. The about page, Login page, and the contact page were in separate folders but mainly the pages of the navbar are available in the same folder and due to multiple folders there is duplicacy in the data thatswhy I put them in a single folder.

NOW ALL THE PAGES LOOK LIKE THIS:

1. HOME PAGE
image
image

2. ABOUT PAGE
image
image

3. LOGIN PAGE
image

Please check @nilisha-jais . Thanks!

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Hey @RahulBansal0502 please don't change the footer of the main index.html file(the one with glowing effect) as that is finalized and would be added in every page. 
And please solve the conflicts

**Comment by RahulBansal0502** [comment]
I have only changes the colour @nilisha-jais from black to green. Effect is same. On hovering it will glow.

**Comment by nilisha-jais** [comment]
Please check [this](https://deploy-preview-402--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp) as it is not visible in the preview of the deployed link

**Comment by RahulBansal0502** [comment]
@nilisha-jais I think now this is fine.

**Comment by nilisha-jais** [comment]
Yes looks fine now! Just resolve the conflicts it's good to merge

**Comment by RahulBansal0502** [comment]
Only you can resolve the conflicts @nilisha-jais as only you have the write access.

**Pull request closed without merging**
