### PR TITLE
Issue is resolved

### LINKED ISSUE #252: Footer should be improvised.
## 🚀 Feature
Footer will be improvised as we will add contact us detail in footer and social media icons too.
@nilisha-jais Please try to assign me this issue

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

### PR DESCRIPTION
**Pull request by tanya070820**
### Description

(Write your answer here.)

### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Please add the issue you were assigned

**Comment by tanya070820** [comment]
#252 Footer should be improvised @nilisha-jais

**Comment by nilisha-jais** [comment]
Hey @tanya070820 just check in the preview of the deployed link. The footer does'nt look fine

**Comment by tanya070820** [comment]
Ok Ma'am

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Hey @tanya070820 , just checked your pr. The website has broken badly. Can you please look once ?

**Comment by tanya070820** [comment]
@niloysikdar What happen Sir I am not getting your point.

**Comment by niloysikdar** [comment]
Go to [this link](https://deploy-preview-282--musicophilia.netlify.app/) and see the changes.

**Comment by tanya070820** [comment]
Sir very sorry for the mistake but can you please help me how can I improve it

**Comment by niloysikdar** [comment]
No worries @tanya070820 , we can definitely fix that.  Just pull the changes first. Then you are good to go.

**Comment by tanya070820** [comment]
@niloysikdar Please have a look on the final one

**Comment by niloysikdar** [comment]
I have seen the changes, but there are so many things which aren't working. You can also see through the deployed link.

**Comment by tanya070820** [comment]
@niloysikdar @nilisha-jais Please have a look .

**Comment by tanya070820** [comment]
Conflict is resolved please have a look.

**Comment by niloysikdar** [comment]
Hey @tanya070820 , if you please open the deployed link you can see that the preloader, navbar, footer, nothing is working, it is causing too many bugs on the website. @nilisha-jais  @harshita2216 @Keerthanam1029 please review this pr.

**Comment by tanya070820** [comment]
Sir as I have compared it from original one then the things which were working their are also working here

**Comment by niloysikdar** [comment]
Okay @tanya070820 ,don't worry. Other reviewers will review this.

**Comment by nilisha-jais** [comment]
@tanya070820 still not working fine. Please  Check <a href="https://deploy-preview-282--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp">this</a>. The preloader and navbar are disrupted.
Do one thing close this pull request, update your fork and then push the changes

**Pull request closed without merging**
