### PR TITLE
Add new feature 124 to the main repo

### PR DESCRIPTION
**Pull request by Sukhseerat-Kaur**
### Description

I added the function of opening the Lets Dance youtube link in the new tab. As it is an external link, it should open in a new tab.

### Checklist

- [ ] I am making a proper pull request, not a spam.
- [ ] I've checked the issue list before deciding what to submit.

### CODE REVIEW

**Review by niloysikdar — APPROVED** [review]
Awesome @Sukhseerat-Kaur

**Comment by niloysikdar** [comment]
Kindly mention your linked issue number @Sukhseerat-Kaur

**Comment by Sukhseerat-Kaur** [comment]
@niloysikdar the issue number was #124

**Comment by niloysikdar** [comment]
Have you checked issue #101 before opening and self-assigning this issue?

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Not a valid pr. @nilisha-jais please look into this.

**Pull request closed without merging**
