### PR TITLE
navbar corrected

### LINKED ISSUE #349: correct the nav bar
## 🐛 Bug Report
Show the active page in the nav bar.

## Add relevant screenshot or video (if any)

In this we cannot find out which page is active 

I would like to change it this was for all the pages.

### PR DESCRIPTION
**Pull request by nisha331**
### Description
Shown the active page in the nav bar
### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

issue #349

### CODE REVIEW

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Please solve the conflicts @nisha331

**Comment by nisha331** [comment]
@niloysikdar still any conflict?

**Comment by niloysikdar** [comment]
Why did you close the pr @nisha331 ?

**Comment by nisha331** [comment]
Sorry @niloysikdar I dont know how and y but  i created a mess here . I opened up a new pr I would be highly obliged if you could have a look to that.

**Pull request closed without merging**
