### PR TITLE
Update index.html

### LINKED ISSUE #211: social media icons
It would be better if we keep social media icons inside the footer . Currently it is above footer.

### PR DESCRIPTION
**Pull request by rishika789**
I was assigned task to transfer social media icons to footer section. I have completed that.

outside footer
inside footer

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Please add a reference to the issue  which you were assigned

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Mention the linked issue @rishika789 , also please solve the conflicts.

**Comment by rishika789** [comment]
#214 
How to solve the conflict ?

**Comment by niloysikdar** [comment]
Watch these videos @rishika789 https://www.youtube.com/watch?v=xNVM5UxlFSA  , https://www.youtube.com/watch?v=JtIX3HJKwfo    

Also mention the number of the issue, not the number of the PR

**Comment by niloysikdar** [comment]
@rishika789 any updates ?

**Comment by rishika789** [comment]
> Mention the linked issue @rishika789 , also please solve the conflicts.

#211

**Comment by rishika789** [comment]
Sir I have resolved the conflicts

**Review by niloysikdar — APPROVED** [review]
Great @rishika789

**Pull request merged**
