### PR TITLE
Bugs in cards of home page and about page fixed

### PR DESCRIPTION
**Pull request by Abhishek-Sahoo**
### Description

1. Karaoke card was not flipping on mouse hover which have been fixed.
2. Card contents of about us page were not aligned properly which have been fixed.

### CODE REVIEW

**Comment by nilisha-jais** [comment]
The about page cards are already fixed. Just fix the karaoke card please!

**Comment by Abhishek-Sahoo** [comment]
> The about page cards are already fixed. Just fix the karaoke card please!

Done.

**Comment by nilisha-jais** [comment]
Please Check [this](https://deploy-preview-432--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp). The footer does'nt seem fine

**Comment by Abhishek-Sahoo** [comment]
> Please Check [this](https://deploy-preview-432--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp). The footer does'nt seem fine

Footer problem fixed. Sorry for inconvenience.

**Review by nilisha-jais — APPROVED** [review]
Looks fine now! Thank you :)

**Pull request merged**
