### PR TITLE
Rishika 4

### LINKED ISSUE #354: footer on each page
footer on each page is different. I would like to make it as in homepage.

homepage

Screenshot (914)

other pages

Screenshot (915)

Screenshot (916)

### PR DESCRIPTION
**Pull request by rishika789**
#354 I have done the changes now footer on all pages are same

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Please check [this](https://deploy-preview-439--musicophilia.netlify.app/contact-us/contact?utm_source=github&utm_campaign=bot_dp). Does'nt seem fine.
There is already same footer in home page and about page. You just need to add the same in contact page. And in the login page there is no need of footer.

**Comment by rishika789** [comment]
> Please check [this](https://deploy-preview-439--musicophilia.netlify.app/contact-us/contact?utm_source=github&utm_campaign=bot_dp). Does'nt seem fine.
> There is already same footer in home page and about page. You just need to add the same in contact page. And in the login page there is no need of footer.

ok I will do

**Comment by niloysikdar** [comment]
Any update @rishika789 ? Otherwise, we need to close this pr.

**Comment by niloysikdar** [comment]
Closed this PR due to inactivity.

**Pull request closed without merging**
