### PR TITLE
issue #335 solved 

### LINKED ISSUE #335: About section's Card Images are not aligned properly
## 🐛 Bug Report

image

In this picture, the cards images are not of proper width, 

What can I do, is to make it of its full width, and make it look awesome, Plz assign me this issue under lgm soc 

Thank You,

### PR DESCRIPTION
**Pull request by ashuydv**
### Description

I've updated about's  card images 

### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

image

### CODE REVIEW

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Please solve the conflicts @ashuydv

**Comment by ashuydv** [comment]
@niloysikdar the conflicts are solved, plz check it !

**Comment by ashuydv** [comment]
@niloysikdar please review it !!

**Comment by nilisha-jais** [comment]
Hey @ashuydv please check the [preview](https://deploy-preview-368--musicophilia.netlify.app/about?utm_source=github&utm_campaign=bot_dp) does'nt  seem fine

**Comment by ashuydv** [comment]
@nilisha-jais I'll work on it, I'll figure it out till tommorow

**Comment by ashuydv** [comment]
I've updated the code, plz review it,...  @nilisha-jais

**Comment by ashuydv** [comment]
Make UI more engaging #337,

1. Added a new loader , plz review it.

**Comment by nilisha-jais** [comment]
@ashuydv the pull request is good to merge you just need to fix the footer. Please check [this](https://deploy-preview-368--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp)
And the preloader looks great!

**Comment by ashuydv** [comment]
on my localhost the loader looks like this,

image

why its expanding ??

image

**Comment by nilisha-jais** [comment]
Check the css maybe something might have been overwritten

**Comment by ashuydv** [comment]
Can U plz explain, what should I fix in footer ?? should I change the background or should i make it like this ?? 
Plz guide me 

footer

**Comment by nilisha-jais** [comment]
Screenshot (41)
The footer looks like this. Just make it of screen size

**Comment by ashuydv** [comment]
Its working now, plz review it now @nilisha-jais

**Comment by nilisha-jais** [comment]
@ashuydv your preloader is working fine now. Just resolve the conflicts I'll merge it. And extremely sorry for the delay.

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Hey @ashuydv , I have viewed your changes. Nothing is working on the main page. Just add the preloader part and remove all.

**Comment by ashuydv** [comment]
ok, will do

**Comment by ashuydv** [comment]
sry, for the delay, review it for the last time

**Comment by nilisha-jais** [comment]
index.html file is fine but it seems that you have made changes in the about page also. Please remove those changes. Check [this](https://deploy-preview-368--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp) .About page looks  different from rest of the pages.

**Comment by ashuydv** [comment]
I've added only cards, I haven't touched navbar in any of them ,  I'll make it fine

**Comment by nilisha-jais** [comment]
Seems fine now. Thank you!

**Review by nilisha-jais — APPROVED** [review]

**Pull request merged**
