### PR TITLE
added preloader

### PR DESCRIPTION
**Pull request by coding-geek21**
### Description

Added preloader

### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#19 
(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Hey @coding-geek21 the preloader remains for too long.....please reduce the time

**Comment by coding-geek21** [comment]
> Hey @coding-geek21 the preloader remains for too long.....please reduce the time

Sure I will change the time ☺️

**Comment by coding-geek21** [comment]
> Hey @coding-geek21 the preloader remains for too long.....please reduce the time

@nilisha-jais I have changed, Please have a look

**Comment by nilisha-jais** [comment]
Looks fine now. Thank you!

**Review by nilisha-jais — APPROVED** [review]

**Pull request merged**
