### PR TITLE
Contact us page

### LINKED ISSUE #414: Footer is not fixed and improving Contact us page
## 🐛 Bug Report
The footer is not fixed and i also want to redesign contact us page

### PR DESCRIPTION
**Pull request by kumarishalini6**
### Description
Close #414 

i have redesign the contact us page

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@nilisha-jais please have a look on this PR

**Comment by kumarishalini6** [comment]
@nilisha-jais please have a look on this PR

**Comment by nilisha-jais** [comment]
The footer and the form is overlapping. Please check

**Comment by kumarishalini6** [comment]
Uploading 127.0.0.1_5501_Contact-Us_contact.html# - Personal - Microsoft​ Edge 2021-06-23 08-18-41.mp4…

**Comment by kumarishalini6** [comment]
> The footer and the form is overlapping. Please check

but it shows fine at my end

**Comment by kumarishalini6** [comment]
https://user-images.githubusercontent.com/69043944/123028020-33ecbd80-d38b-11eb-9d0e-abece8301f6a.mp4

**Comment by nilisha-jais** [comment]
Check [this](https://deploy-preview-418--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp) link
Screenshot (40)

**Comment by nilisha-jais** [comment]
Screenshot (40)
Check [this](https://deploy-preview-418--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp) link

**Comment by kumarishalini6** [comment]
Ok let me check

**Comment by kumarishalini6** [comment]
@nilisha-jais now check it please

**Comment by kumarishalini6** [comment]
@nilisha-jais  please review my PR

**Comment by nilisha-jais** [comment]
Looks fine now. Thank you!

**Review by nilisha-jais — APPROVED** [review]

**Pull request merged**
