### PR TITLE
updated readme issue110

### LINKED ISSUE #110: readme update required

### PR DESCRIPTION
**Pull request by Ayan-thecodeking**
### Description

shorted the Contribution Guidelines without describing images
added project admin section 

let me know @nilisha-jais  if I have do any more changes or updates

### Checklist

- [x] I am making a proper pull request, not a spam.
- [ ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Solve the merge conflicts @Ayan-thecodeking , @nilisha-jais please look into the changes.

**Comment by Ayan-thecodeking** [comment]
> Solve the merge conflicts @Ayan-thecodeking , @nilisha-jais please look into the changes.

hey @niloysikdar I have solved merge conflicts , please look into my changes 
@nilisha-jais 
thank you :)

**Comment by Ayan-thecodeking** [comment]
@niloysikdar can u please describe what are the changes you want

**Comment by niloysikdar** [comment]
@nilisha-jais please look into the changes which you have requested.

**Comment by nilisha-jais** [comment]
Hey @Ayan-thecodeking the readme that we currently have for the project is completely fine. You can just add a section for project admin as that would look great. Even if you find any other flaws you can update that :)

**Pull request closed without merging**
