### PR TITLE
Rishika2

### LINKED ISSUE #329: go buttons
The go buttons will look more catchy if on hovering size of go word increases and background colour changes.

Screenshot (909)

@niloysikdar 
@nilisha-jais

### PR DESCRIPTION
**Pull request by rishika789**
#329 
I have done the changes.
on hovering go buttons text size is increased and background colour is changed.

Screenshot (910)

### CODE REVIEW

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Nice work @rishika789 , just add a transition duration as it isn't providing a good experience for now. You can see [this ](https://www.codegrepper.com/code-examples/css/how+to+slow+down+hover+effect+css)for reference.

**Comment by rishika789** [comment]
> Nice work @rishika789 , just add a transition duration as it isn't providing a good experience for now. You can see [this ](https://www.codegrepper.com/code-examples/css/how+to+slow+down+hover+effect+css)for reference.

okay

**Comment by rishika789** [comment]
i have made the changes.

**Review by niloysikdar — APPROVED** [review]
Working @rishika789 , thanks

**Pull request merged**
