### PR TITLE
PR against issue #291 || Revamp Contact Page 

### PR DESCRIPTION
**Pull request by RahulBansal0502**
image
@nilisha-jais Please check this.

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Hey @RahulBansal0502 are'nt you updating your fork before pushing the changes?

**Comment by RahulBansal0502** [comment]
I have updated but before I push the changes you made changes in the repo.

**Comment by nilisha-jais** [comment]
Check [this](https://www.youtube.com/watch?v=JtIX3HJKwfo) on how to resolve merge conflicts

**Comment by nilisha-jais** [comment]
And you need to use command line to solve the conflict because in your case it is too complex for the web editor to solve

**Comment by RahulBansal0502** [comment]
ok I will check Thanks!

**Comment by RahulBansal0502** [comment]
image
I have not access to write.

**Comment by nilisha-jais** [comment]
Thats what I meant it's  too complex for a web editor to solve it....you need to use command line

**Comment by nilisha-jais** [comment]
Do one thing I'll close both the pr you first pull the changes and then make the pr....conflicts would not occur then. But remember do pull the changes

**Comment by RahulBansal0502** [comment]
Heyy @nilisha-jais can u please help me with how can I resolve this? Because if I will pull the changes then the changes that I have made will also changed so any idea how will I proceed?

**Comment by nilisha-jais** [comment]
You won't loose the code you changed much I guess.....If you fear this thing then you need to solve the merge conflicts.
Take help from the video of How to solve conflicts and solve it using command line

**Pull request closed without merging**
