### PR TITLE
Bottom to top button Added

### PR DESCRIPTION
**Pull request by royalleads15**
A bottom to top button is added

### CODE REVIEW

**Comment by royalleads15** [comment]
Is this is write or I have to do something else.

**Comment by nilisha-jais** [comment]
Was the issue assigned to you?

**Comment by royalleads15** [comment]
I found this issue and this issue is assigned to no one .

**Comment by nilisha-jais** [comment]
Please don't work on a issue or make a pr if it is not assigned to you.

**Comment by royalleads15** [comment]
okkk...then do provide this issue to me under lgm-soc if possible

**Comment by niloysikdar** [comment]
This isn't a valid pr @royalleads15 , you can submit a pr after the assignment of the issues.

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Not a valid pr.

**Review by niloysikdar — COMMENTED** [review]
Not a valid pr.

**Pull request closed without merging**
