### PR TITLE
Easy, medium, hard levels added in Memory Game

### LINKED ISSUE #4: Add levels in the memory game
Add an easy, medium and hard level in the game where the easy level has the least number of cards and hard level the most number of cards.

### PR DESCRIPTION
**Pull request by Jagannath8**
### Description

Easy, medium, hard levels added in Memory Game

Issue #4 

## Add relevant screenshot or video (if any)

hard
medium
easy

### CODE REVIEW

**Comment by niloysikdar** [comment]
Hey @Jagannath8 , I can't find a way to choose the level. Please look into the deployed link.

**Comment by Jagannath8** [comment]
image

**Comment by niloysikdar** [comment]
But please check the deployed link. There is no such option,

**Review by niloysikdar — APPROVED** [review]
LGTM, working fine now.

**Comment by Jagannath8** [comment]
My pr will get merged?

**Comment by Jagannath8** [comment]
My pr will get merged?

**Comment by niloysikdar** [comment]
Yeah sure @Jagannath8

**Comment by nilisha-jais** [comment]
You did a great work @Jagannath8 Thank you :)

**Pull request merged**
