### PR TITLE
Navbar enhancement

### LINKED ISSUE #205: The navbar
## 🚀 Feature

In the navbar, I want to add the hover effect for the home,about and contact us.
Please assign me this issue under lgmsoc.

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
### Description

I have added the hover effect on the navbar and also enhanced the about and contact us.

### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

Fixes #205 

## Add relevant screenshot or video (if any)
before-
image

(Add here)
after-
My Movie 4-2

### CODE REVIEW

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Texts aren't visible while hovering @Khushi-agarwal

**Comment by Khushi-agarwal** [comment]
> Texts aren't visible while hovering @Khushi-agarwal

Should I change the color?

**Comment by niloysikdar** [comment]
Yeah sure @Khushi-agarwal

**Comment by Khushi-agarwal** [comment]
> Yeah sure @Khushi-agarwal

Done the changes @niloysikdar

**Review by niloysikdar — APPROVED** [review]
Great @Khushi-agarwal

**Comment by Khushi-agarwal** [comment]
Will the level tag be added later? @niloysikdar

**Comment by niloysikdar** [comment]
Yes we will assign levels shortly @Khushi-agarwal

**Pull request merged**
