### PR TITLE
Scroll to top button

### LINKED ISSUE #394: Scroll tot op button
## 🚀 Feature

I want to make a scroll tot op button in each and every page 
@nilisha-jais  can i work on this issue

### PR DESCRIPTION
**Pull request by kumarishalini6**
### Description
Scroll to top button was not visible in some pages like home page , dance, artist etc .. 

Closes #394 

### Checklist

- [ ] I am making a proper pull request, not a spam.
- [ ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@nilisha-jais  please have a look on this PR

**Comment by kumarishalini6** [comment]
> ### Description
> Scroll to top button was not visible in some pages like home page , dance, artist etc ..
> 
Closes #394

**Comment by kumarishalini6** [comment]
@nilisha-jais  please review this PR also

**Comment by nilisha-jais** [comment]
Thank you! Looks fine

**Review by nilisha-jais — APPROVED** [review]

**Pull request merged**
