### PR TITLE
Added tabla beats

### LINKED ISSUE #445: Add more tabla beats
## 🚀 Feature
I would like to add more tabla beats in sound folder of tabla

## Motivation
There are only two music provided for tabla and I think there should be more of it.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

### PR DESCRIPTION
**Pull request by SanjuktaSunam**
### Description

I have added some tabla beats

### Checklist

- [ ] I am making a proper pull request, not a spam.
- [ ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by nilisha-jais** [comment]
@SanjuktaSunam what have you done. Could not get your changes. You have added images and two song file but there's no implementation of them.
Please check

**Comment by SanjuktaSunam** [comment]
Ohho sorry mam I did not check that images , I will delete them and then I will pull request but mam I have added tabla beats which are plain tabla beats....

**Comment by SanjuktaSunam** [comment]
Mam please check it once more I have removed images and if there is anything wrong correct me

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Hey @SanjuktaSunam , you haven't changed anything, just added some .m4a files. Also please ensure that you have configured your git correctly, otherwise, you aren't going to get a place in the contributors' list.

**Comment by SanjuktaSunam** [comment]
Hello @niloysikdar I created issue for adding more tabla beats , and I did pull request after adding more 3 tabla beats in my forked repository . So , I am not able to understand about the change you are requesting , if it is about to change .m4a file to .mp3 then I will change it and then I will pull request but if it is about something else then please tell me.

**Comment by nilisha-jais** [comment]
@SanjuktaSunam you have added the mp4 files but you have not implemented that anywhere. What's the use of adding them?
And please configure your git bash as @niloysikdar said!

**Comment by SanjuktaSunam** [comment]
@nilisha-jais  hello mam I have configured git but will you guide me for implementation part ....

**Comment by niloysikdar** [comment]
> Hello @niloysikdar I created issue for adding more tabla beats , and I did pull request after adding more 3 tabla beats in my forked repository . So , I am not able to understand about the change you are requesting , if it is about to change .m4a file to .mp3 then I will change it and then I will pull request but if it is about something else then please tell me.

As @nilisha-jais told, you just added some music files @SanjuktaSunam and didn't implement and link any of them. Can you please tell us what are you trying to do ?

**Comment by SanjuktaSunam** [comment]
I am trying to add 3 tabla beats in Musicophilia ---> tabla ---> sound

**Comment by niloysikdar** [comment]
Okay, @SanjuktaSunam , I think I cannot explain the exact point properly, or you can't understand English. Sirf music files add karne se kya hoga, usko use vi to karna haina ?  Aap sirf music files daalke rakh diye, usko to code se link nahi kiye. Matlab aapka add kiya hua music thori na play ho raha hain. That's the whole point. If you're still confused, then ping me on discord and I will try to explain, maybe through voice channel. Thanks.

**Comment by SanjuktaSunam** [comment]
Oh @niloysikdar  now I got your point you are saying to link with the code , arre bhai yeh baat pehle bata dete toh itna jhanjhat hi nahi hota , chalo koi baat nahi hum samajh gaye hai . Now ,I am working on it. And thanks for your clear explanation.

**Comment by SanjuktaSunam** [comment]
Hey @niloysikdar check it once I have done changes

**Review by niloysikdar — APPROVED** [review]
Thanks @SanjuktaSunam

**Comment by SanjuktaSunam** [comment]
Welcome 😊😊

**Pull request merged**
