### PR TITLE
added cursor animation to the website

### LINKED ISSUE #23: CURSOR ANIMATION
hello mam,
what if the cursor changes from normal cursor to a disco-light cursor ? sounds good right mam :) 
Adding to it,  the cursor will stop once we don't move the cursor.  the theme is music and I thought why not something new this time.
I would like to work on this issue
please assign this to me mam @nilisha-jais  :)

### PR DESCRIPTION
**Pull request by manognyaa**
hello there,
_I have completed the cursor animation. pls guide me if any changes required._ 
:)
issue number : 23
### Description

I have added cursor animation to this website. As the theme is music, I thought `disco light` cursor effect will be looking good. 
Adding to it, I have updated the html and css file.
### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Add relevant screenshot or video (if any)

Here am sharing my project gif
cursor_animation

@niloysikdar

### CODE REVIEW

**Review by niloysikdar — COMMENTED** [review]
Hey, @manognyaa , please mention the linked issue and also provide the necessary screenshot or video.

**Comment by nilisha-jais** [comment]
@manognyaa please squash all the commits in a single one

**Comment by manognyaa** [comment]
> Hey, @manognyaa , please mention the linked issue and also provide the necessary screenshot or video.

ok sir @niloysikdar

**Comment by manognyaa** [comment]
> @manognyaa please squash all the commits in a single one

okay mam @nilisha-jais

**Review by niloysikdar — CHANGES_REQUESTED** [review]
The custom cursor effect isn't working on the whole website, look into this @manognyaa , also please solve the merge conflicts.

**Comment by manognyaa** [comment]
> The custom cursor effect isn't working on the whole website, look into this @manognyaa , also please solve the merge conflicts.

ok sir definitely @niloysikdar

**Comment by niloysikdar** [comment]
Closed the PR due to inactivity.

**Pull request closed without merging**
