### PR TITLE
Added a theme changer button

### PR DESCRIPTION
**Pull request by bharth-stack**
### Description
added button to change theme 
### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

Screenshot (144)

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Hey @bharth-stack please resolve the conflict

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Hey @bharth-stack , why are you toggling between two HTML files ! You can do it using just CSS.

**Comment by niloysikdar** [comment]
Also please mention the linked issue.

**Comment by bharth-stack** [comment]
once check it now

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Great work @bharth-stack , just a small change needed. For the light mode, the texts of the cards aren't clear. Just add another color to the text to increase visibility.

**Comment by bharth-stack** [comment]
Ok

**Comment by bharth-stack** [comment]
check it once

**Review by niloysikdar — APPROVED** [review]
LGTM, add a reference to the linked issue @bharth-stack

**Comment by niloysikdar** [comment]
Also please squash the commits

**Review by niloysikdar — APPROVED** [review]
Please mention the linked issue @bharth-stack

**Comment by bharth-stack** [comment]
> Please mention the linked issue @bharth-stack

could you please tell me what I have to mention exactly

**Comment by bharth-stack** [comment]
> > Please mention the linked issue @bharth-stack
> 
> could you please tell me what I have to mention exactly

the issue created by me is #219

**Pull request merged**
