### PR TITLE
Changed the UI of memory game page

### LINKED ISSUE #225: Memory game changes
## 🚀 Feature

This page doesn't looks good and also the elements are not aligned properly
image
I would like to work on this.

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
### Description

I have added a new background and also corrected the alignment of buttons and added hover effect to them.

### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)
Fixes #225 

## Add relevant screenshot or video (if any)

(Add here)
before-
Screen Shot 2021-06-14 at 12 42 08 PM

after-
Screen Shot 2021-06-15 at 12 44 23 PM
The background used is a gif.

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Changes are not working fine. Browse the preview in the deployed link

**Comment by Khushi-agarwal** [comment]
@nilisha-jais now they are working.

**Comment by nilisha-jais** [comment]
Back button is still not visible. Please check @Khushi-agarwal

**Comment by Khushi-agarwal** [comment]
> Back button is still not visible. Please check @Khushi-agarwal

image
@nilisha-jais  Ma'am it is showing on my browser when I click on the deployed link.

**Comment by nilisha-jais** [comment]
Check <a href="https://deploy-preview-274--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp">this</a> link 
I don't know why is not showing on my browser

**Comment by Khushi-agarwal** [comment]
> Check [this](https://deploy-preview-274--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp) link

Okay ma'am,I will correct it.

**Comment by Khushi-agarwal** [comment]
@nilisha-jais Any other changes required.

**Comment by nilisha-jais** [comment]
Now it's working fine. Thank you :)

**Review by nilisha-jais — APPROVED** [review]

**Pull request merged**
