### PR TITLE
fixes #issue-103

### LINKED ISSUE #103: In band page add text glow effect on Band context .
## 🚀 Feature

In the Band Page, we can add a glowing effect in the band context that suits website Ui {Green and pale green color are used}.

## Add relevant screenshot or video (if any)

The output should like this only glow effect is added no font family is changed.

### PR DESCRIPTION
**Pull request by starrohan999**
### Description

I added glow effect transition that is dimed out every second and change color

### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
issue #103

### CODE REVIEW

**Comment by starrohan999** [comment]
@niloysikdar and @nilisha-jais  please tell me which command is used for keep updating a repo.
Because there is lot more changes in site but not in my local system.
so please tell me.

**Comment by niloysikdar** [comment]
@starrohan999 you can use `git pull upstream main` , but first you need to add the upstream. Check the internet for more details.

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Not working properly on the deployed link @starrohan999

**Comment by starrohan999** [comment]
@niloysikdar  I add upstream. when I run the command git pull upstream main it shows something like that.
2021-06-13 (1)_LI

**Comment by starrohan999** [comment]
please help me setting up.

**Comment by nilisha-jais** [comment]
https://stefanbauer.me/articles/how-to-keep-your-git-fork-up-to-date
I hope this Article  helps you :)
Follow the same steps

**Comment by starrohan999** [comment]
please close this issue.

**Comment by starrohan999** [comment]
is there any slack channel or discord link so I can clear all my doubts

**Comment by starrohan999** [comment]
after following the steps it shows the same thing. what I have to do so now. I want to keep contributing but this thing stop contribution flow

**Comment by starrohan999** [comment]
ye khtm hi hone kaa naam nahi le raha.
@niloysikdar @nilisha-jais

**Comment by nilisha-jais** [comment]
@starrohan999 do one thing.Use the GUI...Ju click "Fetch Upstream"

**Comment by starrohan999** [comment]
again it showing this.
2021-06-14_LI

**Comment by starrohan999** [comment]
@nilisha-jais  can I do one thing that deletes this folder from pc and again clone does it work?

**Comment by niloysikdar** [comment]
Yes you can @starrohan999 , just clone the forked repo again after updating. But it is suspicious why the upstream isn't working in your case :3

**Comment by starrohan999** [comment]
I don't know why these things are always happening to me.
sad life.

**Comment by starrohan999** [comment]
this it works!

**Comment by starrohan999** [comment]
@niloysikdar

**Pull request closed without merging**
