### PR TITLE
Added Hover Effects 

### LINKED ISSUE #130: Hovering Effect
## 🚀 Feature
In the band page , I would like to add hovering effect of zoom out with box shadow

### PR DESCRIPTION
**Pull request by anushka-srivastava22**
### Description
Added Hover Effects on the instruments of band page :
Added a border on the instruments then on hovering color of the border changes from green to light green color and a tranformation is shown outwards with the box shadow shown behind the instruments.

### Checklist

- [ Y ] I am making a proper pull request, not a spam.
- [ Y ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

Hovering Effect on Instruments of Band Page.

## Add relevant screenshot or video (if any)
Link of the video
https://drive.google.com/file/d/1KWGxtxHM5qNmMBS2sXvEY3zmBCSh4hSe/view?usp=drivesdk

### CODE REVIEW

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Mention the linked issue @anushka-srivastava22 , also please solve the merge conflicts.

**Comment by anushka-srivastava22** [comment]
@niloysikdar  I have resolved the conflicts have been resolved.

**Review by niloysikdar — APPROVED** [review]
Awesome @anushka-srivastava22

**Comment by niloysikdar** [comment]
Please mention the linked issue @anushka-srivastava22

**Comment by anushka-srivastava22** [comment]
Hovering Effect #130 
Is the linked issue.

**Pull request merged**
