### PR TITLE
spacing corrected

### PR DESCRIPTION
**Pull request by nisha331**
### Description
 Narrowed height ofnavbar
Corrected spacing between the section end and topic .

### Checklist

-  I am making a proper pull request, not a spam.
-  I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
issue #514

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Not looking fine in mobile view. There's too much top margin!
Screenshot (48)

**Comment by nisha331** [comment]
ok @nilisha-jais will fix that

**Comment by niloysikdar** [comment]
Any update on this @nisha331 ? Now you have to face a large number of merge conflicts. I will suggest to close this pr. Delete this branch, pull the changes to the main branch, and then checkout to a new branch and make changes.

**Comment by nisha331** [comment]
yes @niloysikdar Update - was just trying to figure out the code for mobile view which i m not getting .
Ok will delete the branch and work on a new one.

**Comment by saloni-15** [comment]
Actually, I was working on Navbar to change it's color and navlink hover styling, so I have made it responsive also, and that PR has been merged. 
Navbar is fine now.
You can check here #520

**Comment by niloysikdar** [comment]
Closing this pr for now. Please open a new one if needed @nisha331

**Pull request closed without merging**
