### PR TITLE
added karaoke card

### PR DESCRIPTION
**Pull request by anandalisha**
### Description

Added karaoke feature to the application.

### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

Checked the previous issues and fixed it..now the application is running smoothly 

## Add relevant screenshot or video (if any)

(Ad

d here)

### CODE REVIEW

**Review by niloysikdar — CHANGES_REQUESTED** [review]
The functions aren't working @anandalisha , mention the linked issues, solve the conflicts.

**Comment by anandalisha** [comment]
> The functions aren't working @anandalisha , mention the linked issues, solve the conflicts.
I'll fix it by today @niloysikdar

**Comment by anandalisha** [comment]
> The functions aren't working @anandalisha , mention the linked issues, solve the conflicts.

@niloysikdar fixed the issue

**Comment by anandalisha** [comment]
@niloysikdar @nilisha-jais can u see the changes I made and merge it.

**Comment by nilisha-jais** [comment]
Looks great @anandalisha . Thank you :)
You can add your feature in the main index.html file

**Review by nilisha-jais — APPROVED** [review]

**Pull request merged**
