### PR TITLE
navbar corrected

### LINKED ISSUE #349: correct the nav bar
## 🐛 Bug Report
Show the active page in the nav bar.

## Add relevant screenshot or video (if any)

In this we cannot find out which page is active 

I would like to change it this was for all the pages.

### PR DESCRIPTION
**Pull request by nisha331**
### Description
Navbar corrected

### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
#349

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Hey @nisha331 please pull the changes

**Comment by nisha331** [comment]
@nilisha-jais is it fine now ?

**Comment by nilisha-jais** [comment]
Yes it's fine but I cannot see any changes. What did you change

**Comment by nisha331** [comment]
I just tried removing the conflict from here itself . Its working right? I don't know I just tried it. @nilisha-jais

**Review by niloysikdar — CHANGES_REQUESTED** [review]
The conflicts have solved @nisha331 but I can't see any changes in the navbar.

**Pull request closed without merging**
