### PR TITLE
Added Guess the Singer Game for Issue 40 in main repo

### PR DESCRIPTION
**Pull request by shreyansh30saxena**
Reference to issue number #40 

This is a game developed using HTML, CSS and Vanilla JAVASCRIPT.
A picture will be shown to the user and they will have 4 options to choose and once they click, they will get to know whether the answer was right or not and if it was wrong then what is the correct answer.
The user will have 3 categories to choose from
1. Bollywood (Images of only bollywood singers will be shown)
2. Hollywood (Images of only hollywood singers will be shown)
3. Punjabi (Images of only punjabi singers will be shown)

The UI is responsive for most of the devices.

### CODE REVIEW

**Review by niloysikdar — APPROVED** [review]
Awesome work @shreyansh30saxena

**Comment by nilisha-jais** [comment]
@shreyansh30saxena please add the section of your new feature in the main index.html file

**Comment by shreyansh30saxena** [comment]
Sure I'll add.
Do I need to create a separate issue for that and then again Pull Request for that issue?

**Comment by nilisha-jais** [comment]
Yes create an issue and make the pr

**Pull request merged**
