### PR TITLE
Added Navbar and Footer in Login page

### LINKED ISSUE #338: Add navbar in About and Login page
## 🚀 Feature

Hey @nilisha-jais @niloysikdar 
I would like to add navbar in about and login page
Please assign it to me.
Thanks

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

### PR DESCRIPTION
**Pull request by Shaishav0507**
### Description

Fixes: #338 
I have added navbar and footer in login page.
Please check and update.
Thanks

### Checklist

- [ ] I am making a proper pull request, not a spam.
- [ ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Check the alignment of the footer properly @Shaishav0507

**Comment by Shaishav0507** [comment]
> Check the alignment of the footer properly @Shaishav0507

In code or while running

**Comment by niloysikdar** [comment]
Check the deployed link @Shaishav0507

**Comment by niloysikdar** [comment]
Check this @Shaishav0507

**Comment by Shaishav0507** [comment]
Ok I'll do the changes

**Comment by Shaishav0507** [comment]
@niloysikdar Please check now.

**Comment by niloysikdar** [comment]
Why did you close the pr @Shaishav0507 ?

**Comment by Shaishav0507** [comment]
@niloysikdar I thought u were unhappy with the results.
Plus I think there is no need to add the footer in login page as login page looks amazing and it will just not suit with it.
If you still want I can go ahead and do that.

**Comment by niloysikdar** [comment]
Yes, there is no need for the footer. But we need a navbar for navigating to the pages.

**Comment by Shaishav0507** [comment]
Ok I will do that

**Comment by niloysikdar** [comment]
Great, just open another pr regarding the same. I am reopening the issue.

**Comment by Shaishav0507** [comment]
Sure

**Pull request closed without merging**
