### PR TITLE
Proper documentation and Indentation of code

### LINKED ISSUE #147: Add facebook, instagram and twitter login page
## 🚀 Feature

Whenever a user clicks on any of logo of facebook , instagram and twitter he/she get redirected to respective page . Suppose a user clicks on insta logo , after click he must reach insta page of musicophilia .

## Motivation

The motivation for issue come from acessing various music sites .

## Pitch

This feature must be implemented because if anyone wants to connect with musicophilia he/she can do so .

### LINKED ISSUE #149: Proper documentation and indentation of code
## 📚 Documentation

Proper documentation is very important so that anyone can easily understand it and work upon it .
for Ex .
1. All the css property must be kept in .css file which is not in index.html
2. Proper Comments and indentation of code . etc

### PR DESCRIPTION
**Pull request by royalleads15**
### Description
Documentation and indentation of code done in all files . 
### Checklist

- [ yes ] I am making a proper pull request, not a spam.
- [yes ] I've checked the issue list before deciding what to submit.

### CODE REVIEW

**Comment by royalleads15** [comment]
@niloysikdar review this pr and if write then merge it.

**Comment by royalleads15** [comment]
@niloysikdar review this pr and if right merge it .

**Comment by royalleads15** [comment]
@niloysikdar Login page of  social networking sites added in footer which will open in new tab. Review this PR and If right then merge it .

**Comment by nilisha-jais** [comment]
Please add a reference to the issue which was assigned to you

**Comment by royalleads15** [comment]
I have assigned issue #149 and #147

**Review by nilisha-jais — APPROVED** [review]

**Comment by nilisha-jais** [comment]
Thank you @royalleads15 :)

**Pull request merged**
