### PR TITLE
Issue 44

### LINKED ISSUE #44: change the border color of images in Music box section.
change the border color of images in the Music box section. and also increase  box shadow of container.
Before

After
Untitled design

### PR DESCRIPTION
**Pull request by starrohan999**
### Description

Solve the issue -44 related to the music section artist image border color and also increase the box-shadow property of the player if it feels awesome and Better UI.

### Checklist

-  I am making a proper pull request, not spam.
- I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
 
Issue -44.

## Add relevant screenshot or video (if any)
Before:

After:

### CODE REVIEW

**Review by niloysikdar — CHANGES_REQUESTED** [review]
@starrohan999 , please add `min-height: 100vh;` to the class `app-wrapper`

**Comment by starrohan999** [comment]
Ok @niloysikdar

**Comment by starrohan999** [comment]
Hi @niloysikdar, Actually I have a question. can I simply shift to the Issue-44 branch and made changes and commit it.
then after push it. 
is it good or any other way please explain me. @niloysikdar

**Comment by starrohan999** [comment]
So i can do it ASAP.

**Comment by niloysikdar** [comment]
> Hi @niloysikdar, Actually I have a question. can I simply shift to the Issue-44 branch and made changes and commit it.
> then after push it.
> is it good or any other way please explain me. @niloysikdar

Yes you can

**Comment by starrohan999** [comment]
ok, thank you so much.

**Comment by starrohan999** [comment]
I added the property please check @niloysikdar

**Review by niloysikdar — APPROVED** [review]
LGTM

**Comment by starrohan999** [comment]
Thank you so much @niloysikdar and @nilisha-jais

**Pull request merged**
