### PR TITLE
Made website Responsive

### LINKED ISSUE #155: Website is not looking good in mobile View and toggle is also not working
will you please assign me this @nilisha-jais  under LGM-soc'21

### PR DESCRIPTION
**Pull request by Kartikey0205**
fixes #155
### Description
There was a bug in webpage which I had resolve now (Issue no. #155 )

* `Previous Website is not responsive in other devices , I @kartikey0205 (Kartikey Dubey) made it responsive` 
*  `Previous Toggle or say Hamburger menu is not working  , now I had written some of JavaScript file , updating some styling and a done some Dom manipulation and make it works!` 
### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
Issue is #155
Making Website Responsive and adding functionality of hamburger menu bar/ toggling 

## Add relevant screenshot or video (if any)
# To check what I had done click below
[Musicophilia](https://kartikey0205.github.io/Musicophilia/)

@niloysikdar @nilisha-jais  please go though it and review it .
and also add my name in Contribution section (Readme Section)
and also please mark a level for this work under Lgm-soc'21

### CODE REVIEW

**Review by nilisha-jais — APPROVED** [review]

**Comment by nilisha-jais** [comment]
Thank you for the fix @Kartikey0205 :)

**Comment by nilisha-jais** [comment]
Hey @Kartikey0205 please make a fresh pull request. I guess the index.html file was all messed up so I had to revert the pr.

**Comment by Kartikey0205** [comment]
@nilisha-jais so what I have to do right now exactly ?
I want to create a new issue or what .

you had revert the PR . but it showing me already merged ,
issue is closed so how can I create a new pull request.

@nilisha-jais sorry but really I don't understand what to do exactly

**Comment by nilisha-jais** [comment]
Okay do one thing...I am making a new issue, take it up and push the changes.

**Pull request merged**
