### PR TITLE
Improved spacing in all the pages

### LINKED ISSUE #484: Space between navbar  and  main section
Can I add some space below the navbar as it will make things more clean and enhance user experience. I will add it in home page, login page and contact us page.

## Screenshot

music

### PR DESCRIPTION
**Pull request by RiyaGupta89**
### Description

Added spacing in all the three pages and made them look cleaner.

### Checklist

- [✔️] I am making a proper pull request, not a spam.
- [✔️] I've checked the issue list before deciding what to submit.

## Add relevant screenshot or video (if any)

spacing-correct

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Hey @RiyaGupta89 what files have you added please check!

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Remove the unnecessary files @RiyaGupta89

**Comment by RiyaGupta89** [comment]
@nilisha-jais Can you name the files please?

**Comment by RiyaGupta89** [comment]
@nilisha-jais  @niloysikdar  Hey, I've removed all the unnecessary files that got added by mistake by me. Please review my PR.

**Review by niloysikdar — APPROVED** [review]
Looks nice @RiyaGupta89

**Pull request merged**
