### PR TITLE
Signup page

### PR DESCRIPTION
**Pull request by jugeshraghav**
### Description

I have created a database for signup page using nodejs and mongodb

### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#426

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by jugeshraghav** [comment]
please have a look @nilisha-jais @niloysikdar and so sorry for being this much late .

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Hey @jugeshraghav , since you are using nodejs environment, the app will not run directly like this. Instead of doing that you can make the nodejs app which we can host separately and then we can call that API while clicking login/sign up button. @nilisha-jais your views please.

**Comment by nilisha-jais** [comment]
@jugeshraghav this won't work. Follow what @niloysikdar said!

**Comment by jugeshraghav** [comment]
Okay

**Comment by niloysikdar** [comment]
Closing this

**Pull request closed without merging**
