### PR TITLE
Complete band

### LINKED ISSUE #173: Adding More instruments in the band section and enhancing the band page.
## 🚀 Feature

The band section can have more instruments and user can also see which keys work for which instrument.

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

Now user doesn't know that the band can also be played with he keyboard keys. We can add some feature which enables the user to know about which key of keyboard corresponds to which instrument. 
Also we can add some more instruments in the drum.

## Add relevant screenshot or video (if any)

(Add here)

### PR DESCRIPTION
**Pull request by jugeshraghav**
### Description

I have made some changes in the band page. The user now is able to know which keys are used to play the drum and i have also added a footer.

### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#173 

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by jugeshraghav** [comment]
please give it a look and suggest me if i can improve something. @nilisha-jais @niloysikdar

**Review by niloysikdar — CHANGES_REQUESTED** [review]
The footer doesn't look good to me. Also, you have changed the color scheme @jugeshraghav . Please look into this pr @nilisha-jais

**Comment by jugeshraghav** [comment]
I will surely make some changes 😇

**Comment by jugeshraghav** [comment]
Screenshot (90)
Screenshot (91)

Is this okay ! OR do I have to make more changes.

**Comment by niloysikdar** [comment]
The body seems fine, for the footer, you can remove the services and contact us part from there. Also the back button should be on the top left corner. @jugeshraghav

**Comment by jugeshraghav** [comment]
Okay

**Comment by jugeshraghav** [comment]
can i use the footer of the index page here.

**Comment by nilisha-jais** [comment]
yes use that only

**Comment by jugeshraghav** [comment]
I was thinking to add the social icons inside the footer.

**Comment by jugeshraghav** [comment]
I have changes the band page as guided by you and made it responsive also added the social media icons in the footer.
But I removed the glow effect on the band title because it was hiding the tagline below it.
Please review it and tell me if I can do something better.

**Comment by jugeshraghav** [comment]
This is the current band page 
Screenshot (99)

This is the band page I have modified.
Screenshot (100)
Screenshot (101)

I made the PR yesterday and It has not been reviewed till now, If I have to make further changes do I have to make a pull request first. @niloysikdar @nilisha-jais

**Comment by nilisha-jais** [comment]
@jugeshraghav the footer we currently have in the website looks  completely fine. Just do one thing put the social media icons inside the footer and there's no need of extra icon of telegram. You can add github if you wish.
And  sorry for the late review. If you want to ask something related to changes please prefer slack because we have have a lots of comments here it's certainly difficult to manage all of them.

**Comment by jugeshraghav** [comment]
Kindly review the PR. As I am not able to open other issues.

**Comment by niloysikdar** [comment]
Sorry @jugeshraghav for the delay, doing it right now.

**Review by niloysikdar — APPROVED** [review]
Great work @jugeshraghav

**Pull request merged**
