### PR TITLE
Improved NavBar and Toggle

### PR DESCRIPTION
**Pull request by gunjan-g**
### Description
Fixes issue #499 
The navbar is more proper according to UI design and toggle button is visible in all the pages

### Checklist
- [ yes] I am making a proper pull request, not a spam.
- [ yes] I've checked the issue list before deciding what to submit.

## Add relevant screenshot or video (if any)
Spacing between navbar
image

Toggle Button is now visible properly
image

### CODE REVIEW

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Hey @gunjan-g , please configure your local git with proper credentials. We are getting commits from your second account -  @Gunjangupta12

**Comment by gunjan-g** [comment]
> Hey @gunjan-g , please configure your local git with proper credentials. We are getting commits from your second account - @Gunjangupta12

sir, just by changing config, will it be applicable to all my previous commits as well?

**Comment by niloysikdar** [comment]
No @gunjan-g , it will not reflect any changes to your previous commits. I didn't notice it earlier, noticed now, sorry :)

**Comment by gunjan-g** [comment]
> No @gunjan-g , it will not reflect any changes to your previous commits. I didn't notice it earlier, noticed now, sorry :)

sir, sorry i didn't know but that wouldn't count as my contribution in lgmsoc then

**Comment by niloysikdar** [comment]
> > No @gunjan-g , it will not reflect any changes to your previous commits. I didn't notice it earlier, noticed now, sorry :)
> 
> sir, sorry i didn't know but that wouldn't count as my contribution in lgmsoc then

Not sure @gunjan-g , but your main (this one) account hasn't been added to the contributors' list as you didn't push code from this account.

**Comment by niloysikdar** [comment]
Capture

**Comment by gunjan-g** [comment]
> > > No @gunjan-g , it will not reflect any changes to your previous commits. I didn't notice it earlier, noticed now, sorry :)
> > 
> > 
> > sir, sorry i didn't know but that wouldn't count as my contribution in lgmsoc then
> 
> Not sure @gunjan-g , but your main (this one) account hasn't been added to the contributors' list as you didn't push code from this account.

sir i'll do the required changes and then push the code again

**Comment by niloysikdar** [comment]
Sure @gunjan-g , let me know if you need any help.

**Comment by gunjan-g** [comment]
Sir, please consider the new pr made

**Pull request closed without merging**
