### PR TITLE
Added footer in Login page

### LINKED ISSUE #338: Add navbar in About and Login page
## 🚀 Feature

Hey @nilisha-jais @niloysikdar 
I would like to add navbar in about and login page
Please assign it to me.
Thanks

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

### PR DESCRIPTION
**Pull request by Shaishav0507**
### Description

Fixes: #338 
Hey @nilisha-jais @niloysikdar 
I have added the footer in login page.
Please check and update.
Thanks

### Checklist

- [x] I am making a proper pull request, not a spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by Shaishav0507** [comment]
I overwrote the files in case you get confused while seeing the files changed

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Hey @Shaishav0507 , We already have a beautiful [login page](https://musicophilia.netlify.app/login/login.html), please pull these changes, don't overwrite the files. Just add the footer.

**Comment by Shaishav0507** [comment]
@niloysikdar everything is same.
Nothing is changed. It's just overwritten

**Comment by niloysikdar** [comment]
Visit [this link](https://deploy-preview-347--musicophilia.netlify.app/login/login?utm_source=github&utm_campaign=bot_dp)

**Comment by Shaishav0507** [comment]
> Visit [this link](https://deploy-preview-347--musicophilia.netlify.app/login/login?utm_source=github&utm_campaign=bot_dp)
> 
> 

What is issue in this?

**Comment by Shaishav0507** [comment]
Could you please tell

**Comment by Shaishav0507** [comment]
Got it 
You got the new login UI
I'll update and create new PR.

**Pull request closed without merging**
