### PR TITLE
nav bar and hamburger view changed

### LINKED ISSUE #351: view of hambarger menu
Capture
look need to be changed

### PR DESCRIPTION
**Pull request by nitishapiplani**
issue#351
changing view of hamburger menu (enhance look)

m1
m2

### CODE REVIEW

**Comment by nilisha-jais** [comment]
@nitishapiplani please fill the pr template properly .Mention the changes you made and issue that was assigned to you.

**Comment by nitishapiplani** [comment]
> @nitishapiplani please fill the pr template properly .Mention the changes you made and issue that was assigned to you.

done plzz check

**Comment by nitishapiplani** [comment]
> > @nitishapiplani please fill the pr template properly .Mention the changes you made and issue that was assigned to you.
> 
> done plzz check

@nilisha-jais

**Comment by nilisha-jais** [comment]
There's two button for contact and login. Check <a href="https://deploy-preview-356--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp">this</a>. Also please add suitable hover effects.

**Comment by nitishapiplani** [comment]
> There's two button for contact and login. Check [this](https://deploy-preview-356--musicophilia.netlify.app/?utm_source=github&utm_campaign=bot_dp). Also please add suitable hover effects.
okk

**Comment by nitishapiplani** [comment]
plzz check now @nilisha-jais

**Comment by nilisha-jais** [comment]
Please fix this even @nitishapiplani 
Screenshot (37)

**Comment by nitishapiplani** [comment]
But I thing we should not add this button here

**Comment by nilisha-jais** [comment]
That's what I mean add this as a nav item

**Comment by nitishapiplani** [comment]
plzz check

**Comment by nitishapiplani** [comment]
@nilisha-jais

**Comment by nilisha-jais** [comment]
Looks good to me! Thank you

**Review by nilisha-jais — APPROVED** [review]

**Pull request merged**
