### PR TITLE
Piano game

### LINKED ISSUE #454: piano game
## 🚀 Feature

I want to add a piano game where piano makes some random sounds after starting the game and the player have the guess the sound exactly by clicking the piano buttons.

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

### PR DESCRIPTION
**Pull request by bharth-stack**
### Description

(Write your answer here.)

### Checklist

- [ ] I am making a proper pull request, not a spam.
- [ ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by nilisha-jais** [comment]
@bharth-stack please configure your local git in a correct manner!

**Comment by niloysikdar** [comment]
Hey @bharth-stack , can you please explain in detail what the game is actually doing and how to play it?

**Comment by bharth-stack** [comment]
> Hey @bharth-stack , can you please explain in detail what the game is actually doing and how to play it?

step -1: Click the play button. After clicking the play button it will start playing some random sounds.

step -2: After completing  step-1 start button appears beside the play button. The piano buttons won't work until you click the start button.

step-3: Click start button to start the game. You will have three chances of playing wrong button if you use all those three you lost the game . If you want to play again you can click again.

step-4: If you want to hear the sounds again you can click play button again to hear them.

Step-5 : If you want to restart the game you can click restart to change the sounds.

**Comment by nilisha-jais** [comment]
@bharth-stack Got it now! But I guess your local git is not configured properly. Please look into it

**Comment by bharth-stack** [comment]
> @bharth-stack Got it now! But I guess your local git is not configured properly. Please look into it

please tell me how to do it

**Comment by nilisha-jais** [comment]
Hey @bharth-stack follow [this](https://youtu.be/J_Clau1bYco). Just make sure that you use the same email that you have used for your GitHub profile to setup your git bash.

**Comment by bharth-stack** [comment]
> Hey @bharth-stack follow [this](https://youtu.be/J_Clau1bYco). Just make sure that you use the same email that you have used for your GitHub profile to setup your git bash.

I configured my local git so do you want to push again the project

**Comment by niloysikdar** [comment]
You can push one commit to this same branch @bharth-stack

**Comment by bharth-stack** [comment]
> You can push one commit to this same branch @bharth-stack

So shall I close the pull request and push again?

**Comment by niloysikdar** [comment]
No @bharth-stack , don't close it. though if we merge your pr, you won't be added to the collaborators' list.

**Comment by bharth-stack** [comment]
> No @bharth-stack , don't close it. though if we merge your pr, you won't be added to the collaborators' list.

ok 

so what I have to do?

**Comment by niloysikdar** [comment]
> > No @bharth-stack , don't close it. though if we merge your pr, you won't be added to the collaborators' list.
> 
> ok
> 
> so what I have to do?

You can make any minor change and push to this same branch after configuring your git properly

**Comment by bharth-stack** [comment]
> > > No @bharth-stack , don't close it. though if we merge your pr, you won't be added to the collaborators' list.
> > 
> > 
> > ok
> > so what I have to do?
> 
> You can make any minor change and push to this same branch after configuring your git properly

Please check it once I made some minor change and pushed again.

**Review by nilisha-jais — APPROVED** [review]
LGTM! Thank you :)

**Pull request merged**
