### PR TITLE
fixes issue-103 with glow effect in band context

### LINKED ISSUE #103: In band page add text glow effect on Band context .
## 🚀 Feature

In the Band Page, we can add a glowing effect in the band context that suits website Ui {Green and pale green color are used}.

## Add relevant screenshot or video (if any)

The output should like this only glow effect is added no font family is changed.

### PR DESCRIPTION
**Pull request by starrohan999**
### Description

#191 

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

### CODE REVIEW

**Comment by starrohan999** [comment]
Please review it @niloysikdar and @nilisha-jais.
Thank you so much for helping me to figure out upstream problem.

**Comment by starrohan999** [comment]
this level 1 pr level

**Review by niloysikdar — APPROVED** [review]
Great @starrohan999

**Pull request merged**
