### PR TITLE
Fixes Issue -63

### LINKED ISSUE #63: In Footer section there is No year mention related to Copyright.
## 🐛 Bug Report

In the Footer section, there is No year mention related to Copyright.

## Add relevant screenshot or video (if any)
2021-06-10 (4)_LI

### PR DESCRIPTION
**Pull request by starrohan999**
### Description

Added year section in copyright section that presents in the footer.

### Checklist

- I am making a proper pull request, not spam.
- I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

Issue-63

## Add relevant screenshot or video (if any)
2021-06-11 (1)_LI

### CODE REVIEW

**Comment by starrohan999** [comment]
@niloysikdar please tell me what is conflicts that are getting?

**Comment by niloysikdar** [comment]
Hey, @starrohan999 please solve the merge conflicts. You can watch [this video](https://www.youtube.com/watch?v=JtIX3HJKwfo).

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Solve the merge conflicts.

**Comment by niloysikdar** [comment]
Also mention the issue like #issue-number

**Comment by nilisha-jais** [comment]
I have resolved the conflict this time @starrohan999  but from next time onwards first update your fork and then make a pull request in order to avoid merge conflicts

**Comment by starrohan999** [comment]
@niloysikdar  please tell me what changes that I have to done?

**Pull request merged**
