### PR TITLE
Issue #64 |  Added animation to the icons

### LINKED ISSUE #64: Replace Emojis with Animated Box Icons
## 🚀 Feature

I think we should replace those Emojis present on Cards, and use some animated icons which would make it look better and a bit more interactive to the User.

### PR DESCRIPTION
**Pull request by utkarshgoel10**
### Description

I've added an infinite shaking animation to the icons on the Home Page to make them look a bit more interactive.
I have ensured that I have maintained the code consistency while solving this issue.
Please review it.

## Related Issues or Pull Requests
<a href="https://github.com/nilisha-jais/Musicophilia/issues/64">64</a>

## Sample Video

https://user-images.githubusercontent.com/66838142/121568749-a7163b80-ca3d-11eb-9d87-f01d6b1954d4.mp4

### CODE REVIEW

**Review by niloysikdar — APPROVED** [review]
LGTM

**Comment by utkarshgoel10** [comment]
So, do I need to do anything else about this issue, or is this sufficient for merging? @niloysikdar @nilisha-jais

**Comment by nilisha-jais** [comment]
There's a merge conflict. Please resolve it

**Comment by utkarshgoel10** [comment]
Please check it @nilisha-jais, I've resolved all the conflicts and all the checks have been passed.

**Comment by nilisha-jais** [comment]
Looks great! Thank you @utkarshgoel10 :)

**Pull request merged**
