### PR TITLE
artistInfoFileUpdated

### LINKED ISSUE #249: In artistDetails, info is not working properly
## 🐛 Bug Report

In artist Detail section on clicking info, it does not redirect to info page for the singer.
As a LGMSOC21 participant, assign me to fix this issue

### PR DESCRIPTION
**Pull request by Pratik57**
### Description

Issue related to artist info
Now artist info will redirect to correct page

### Checklist

- [X] I am making a proper pull request, not a spam.
- [X] I've checked the issue list before deciding what to submit.

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Please reference the issue you were assigned

**Comment by Pratik57** [comment]
> Please reference the issue you were assigned
@nilisha-jais 
issue no: 249
https://github.com/nilisha-jais/Musicophilia/issues/249#issue-920486769

People are changing the content also with the design 😕, and you merged them too.
So how i will solve this conflict now ? If you have any idea, suggest me please ☹

**Comment by nilisha-jais** [comment]
You should have filled the pr template properly!
Please follow <a href="https://www.youtube.com/watch?v=JtIX3HJKwfo">this</a> on how to resolve the conflicts

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Just try to solve the conflicts and we are good to go @Pratik57

**Comment by Pratik57** [comment]
@niloysikdar Yes finally i did it😅 
@nilisha-jais Actually i filled pr template correctly but when you had merged else pr lead to conflict on my page. However thanks, the link is very useful 😀

**Review by niloysikdar — CHANGES_REQUESTED** [review]
@Pratik57 can you please tell us how to view info about the artists?

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Add the icon to the all cards @Pratik57

**Review by niloysikdar — APPROVED** [review]
Great @Pratik57

**Comment by Pratik57** [comment]
> Great @Pratik57

Thanks @niloysikdar  😀

**Pull request merged**
